workflows:
  android-release-workflow:
    name: Shofyou Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - keystore_credentials # سنعرف هذه المجموعة في واجهة كود ماجيك
      vars:
        PACKAGE_NAME: "com.shofyou.app"
      java: 17
    scripts:
      - name: Generate Keystore if not exists
        script: |
          # هذا السطر ينشئ مفتاح توقيع جديد إذا لم ترفع واحدًا
          if [ ! -f "keystore.jks" ]; then
            keytool -genkey -v -keystore keystore.jks \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -alias shofyou_alias -storepass $CM_KEYSTORE_PASSWORD \
              -keypass $CM_KEY_PASSWORD -dname "CN=Shofyou, OU=Dev, O=Shofyou, L=City, S=State, C=US"
          fi
      - name: Build Android Release (APK & AAB)
        script: |
          chmod +x gradlew
          # بناء نسخة الـ APK ونسخة المتجر AAB
          ./gradlew assembleRelease bundleRelease
    artifacts:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab
      - keystore.jks # سيظهر لك الملف هنا لتحميله وحفظه للأبد
    publishing:
      email:
        recipients:
          - your-email@example.com
